status = error
name = FraudAppLogConfig

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

rootLogger.level = warn
rootLogger.appenderRef.stdout.ref = STDOUT

logger.fraud.name = com.fraud.app
logger.fraud.level = info
logger.fraud.additivity = false
logger.fraud.appenderRef.stdout.ref = STDOUT
