apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: retail-promotion
spec:
  sparkConf:
    spark.sql.shuffle.partitions: "8"
  driver:
    cores: 1
    memory: "1g"
    env:
      - name: JAVA_TOOL_OPTIONS
        value: "-Denv=dev"
  executor:
    cores: 1
    instances: 1
    memory: "1g"
    env:
      - name: JAVA_TOOL_OPTIONS
        value: "-Denv=dev"
