status = warn
name = DrHaDemoLog4j2

appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n

rootLogger.level = warn
rootLogger.appenderRef.console.ref = ConsoleAppender

logger.dr.name = com.retailbank.dr
logger.dr.level = info
logger.dr.additivity = false
logger.dr.appenderRef.console.ref = ConsoleAppender
