status = warn
name = PropertiesConfig

appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1} - %m%n

rootLogger.level = info
rootLogger.appenderRef.console.ref = ConsoleAppender

logger.spark.name = org.apache.spark
logger.spark.level = warn

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn

logger.bankcorp.name = com.bankcorp.dataeng
logger.bankcorp.level = info
