apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: retail-prod
resources:
  - ../../base
namePrefix: prod-

images:
  - name: acrretailbank.azurecr.io/retail-platform-promotion-model
    newTag: PLACEHOLDER_GIT_SHA  # identical digest promoted from test after sign-off, see .github/workflows/promote.yml

patches:
  - path: patch-sparkapplication.yaml
    target:
      kind: SparkApplication
      name: retail-promotion
  - path: patch-serviceaccount.yaml
    target:
      kind: ServiceAccount
      name: spark-driver
