package com.frauddetection.model;

import java.io.Serializable;

/**
 * FRAUD DETECTION PIPELINE - Fraud Alert Domain Model
 *
 * Represents a detected fraud alert generated by our pipeline.
 * This is what the fraud operations team acts upon.
 *
 * Business Context:
 * - Alert must be generated within 5 seconds (P99 SLA)
 * - Alert must include risk score and detection reason
 * - Alert is written to an exactly-once sink (idempotent)
 */
public class FraudAlert implements Serializable {

    private String alertId;
    private String transactionId;
    private String customerId;
    private double amount;
    private String fraudType;          // VELOCITY_ABUSE, GEO_ANOMALY, HIGH_RISK_MERCHANT, etc.
    private double riskScore;          // 0.0 - 1.0
    private String detectionReason;
    private long detectedAtTimestamp;
    private long eventTimestamp;
    private String severity;           // LOW, MEDIUM, HIGH, CRITICAL
    private boolean wasLateEvent;

    public FraudAlert() {}

    public FraudAlert(String alertId, String transactionId, String customerId,
                      double amount, String fraudType, double riskScore,
                      String detectionReason, long eventTimestamp, boolean wasLateEvent) {
        this.alertId = alertId;
        this.transactionId = transactionId;
        this.customerId = customerId;
        this.amount = amount;
        this.fraudType = fraudType;
        this.riskScore = riskScore;
        this.detectionReason = detectionReason;
        this.detectedAtTimestamp = System.currentTimeMillis();
        this.eventTimestamp = eventTimestamp;
        this.wasLateEvent = wasLateEvent;
        this.severity = computeSeverity(riskScore, amount);
    }

    private String computeSeverity(double riskScore, double amount) {
        if (riskScore >= 0.9 || amount > 10000) return "CRITICAL";
        if (riskScore >= 0.75 || amount > 5000)  return "HIGH";
        if (riskScore >= 0.5  || amount > 1000)  return "MEDIUM";
        return "LOW";
    }

    // ======= Getters and Setters =======

    public String getAlertId() { return alertId; }
    public void setAlertId(String alertId) { this.alertId = alertId; }

    public String getTransactionId() { return transactionId; }
    public void setTransactionId(String transactionId) { this.transactionId = transactionId; }

    public String getCustomerId() { return customerId; }
    public void setCustomerId(String customerId) { this.customerId = customerId; }

    public double getAmount() { return amount; }
    public void setAmount(double amount) { this.amount = amount; }

    public String getFraudType() { return fraudType; }
    public void setFraudType(String fraudType) { this.fraudType = fraudType; }

    public double getRiskScore() { return riskScore; }
    public void setRiskScore(double riskScore) { this.riskScore = riskScore; }

    public String getDetectionReason() { return detectionReason; }
    public void setDetectionReason(String detectionReason) { this.detectionReason = detectionReason; }

    public long getDetectedAtTimestamp() { return detectedAtTimestamp; }
    public void setDetectedAtTimestamp(long detectedAtTimestamp) { this.detectedAtTimestamp = detectedAtTimestamp; }

    public long getEventTimestamp() { return eventTimestamp; }
    public void setEventTimestamp(long eventTimestamp) { this.eventTimestamp = eventTimestamp; }

    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }

    public boolean isWasLateEvent() { return wasLateEvent; }
    public void setWasLateEvent(boolean wasLateEvent) { this.wasLateEvent = wasLateEvent; }

    @Override
    public String toString() {
        return String.format("FraudAlert{id='%s', type='%s', severity='%s', score=%.2f, amount=%.2f, reason='%s'}",
                alertId, fraudType, severity, riskScore, amount, detectionReason);
    }
}
